### ISSUE TITLE
README: Add more info about PDFreactor and license

### ISSUE THREAD

**Issue by rfay** [blankse/ddev-pdfreactor#3]
It looks to me like you have to get a license and such, right? But the README doesn't seem to mention that. 

Please add more about PDFreactor - I see there's already a link to it, but maybe just mention what it does and things like that, give a link to how to use it from a CMS.

**Comment by blankse** [comment]
@rfay I add the license link to the readme: https://github.com/blankse/ddev-pdfreactor/commit/ffe5882f46d2f514fcdd4f9447f25c032f378a65

I will add more infos about PDFreactor shortly

**Comment by blankse** [comment]
@rfay I add more infos in this PR #5 

Can you look over it?

**Comment by blankse** [comment]
@rfay Thanks for your input and review
